[options]

A = "**A** - Processes all line types."
B = "**B** - Builds an index containing the first data line of each report. Use this index with subsequent Binary Find operations to speed up processing."
C = "**C(S)** (Windows/Linux/UNIX) - Distinguishes between uppercase and lowercase letters."
E = "**E** - Finds the last occurrence of the character string instead of the first occurrence."
F = "**Fn,n,...** - Specifies the order of sorted fields when searching multiple fields. For n, type the corresponding sort parameter you used for the fields from left to right."
I = "**I[n]** - Uses the index located in report n. Default = 2. The Binary Find command searches the index to determine where to find the character string, assuming that the reports to be searched follow report n."
K = "**K** - Verifies that reports are sorted in ascending order. The command displays the report at the point where it detects the sort order discrepancy and displays a message indicating whether the data is sorted."
N = "**N** - Creates a result containing the last occurrence of each different character string found in the specified field and the number of occurrences of each string."
O = "**O** - Creates a result containing each line on which the specified character string occurs, including trailer lines."
P = "**P** - Includes all types of lines following the last find made. Use only with the N option."
Q = "**Q** - Finds a string that occurs only once in the report for a faster search."
R = "**Rx-y** - Searches reports in a range from report number x to report number y."
S = "**S** - Searches each report separately (data does not have to be sorted across all reports)."
U = "**U** - Sets an update lock on the report in which a find is made or would have been made."
Y = "**Y[(x)]** - Searches for dates in the fields defined by the date format parameter line."
Z = "**Z** - Specifies that blank data lines are sorted with nonblank data lines."
"@" = "**@** - Searches for blank lines or fields at the end of a report."
"/" = "**/** - Searches for the slant (`/`) character."
