[options]
C = "**C** - Centers data within the variable."
H = "**H** - Returns the status of a remote run link."
L = "**L** - Left-justifies data within the variable."
O = "**O** - Converts all uppercase alphabetic characters to lowercase."
P = "**P** - Packs the variable so it contains only significant characters, removing unnecessary leading and trailing spaces."
Q = "**Q** - Loads delimited data from a variable or reserved word into another variable."
R = "**R** - Right-justifies data within the variable."
U = "**U** - Converts all lowercase alphabetic characters to uppercase."
W = "**W** - Loads the variable with the value of a reserved word."
Z = "**Z** - Right-justifies and zero-fills the variable after data is loaded."
